[package]
name = "processing_ffi"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[lib]
name = "processing"
crate-type = ["cdylib", "staticlib"]

[features]
default = []
wayland = ["processing/wayland"]
x11 = ["processing/x11"]

[dependencies]
processing = { workspace = true }
bevy = { workspace = true }
half = "2.7"

[build-dependencies]
cbindgen = "0.29"
