[package]
name = "processing_video"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
nannou_video = { git = "https://github.com/nannou-org/nannou", branch = "bevy-refactor" }
processing_core = { workspace = true }
processing_render = { workspace = true }
